// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoYH4sd1PTHM4Lt5NFZEe-0ANZZXCNI7U',
    appId: '1:920326783426:web:68ffc8510f4238bd07d65b',
    messagingSenderId: '920326783426',
    projectId: 'my-stacked-app',
    authDomain: 'my-stacked-app.firebaseapp.com',
    storageBucket: 'my-stacked-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAct6HqBreZUrL_2fpg-q8pFvYFCjeQSd0',
    appId: '1:920326783426:android:939ffe3369f3fa6d07d65b',
    messagingSenderId: '920326783426',
    projectId: 'my-stacked-app',
    storageBucket: 'my-stacked-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxwiQgtFh44HgCd3kuD1Z_WbcwYC6v5sY',
    appId: '1:920326783426:ios:a1d46f04b97b8b1b07d65b',
    messagingSenderId: '920326783426',
    projectId: 'my-stacked-app',
    storageBucket: 'my-stacked-app.appspot.com',
    iosBundleId: 'com.example.myStackedApp2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxwiQgtFh44HgCd3kuD1Z_WbcwYC6v5sY',
    appId: '1:920326783426:ios:a1d46f04b97b8b1b07d65b',
    messagingSenderId: '920326783426',
    projectId: 'my-stacked-app',
    storageBucket: 'my-stacked-app.appspot.com',
    iosBundleId: 'com.example.myStackedApp2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBoYH4sd1PTHM4Lt5NFZEe-0ANZZXCNI7U',
    appId: '1:920326783426:web:f394cc114831744507d65b',
    messagingSenderId: '920326783426',
    projectId: 'my-stacked-app',
    authDomain: 'my-stacked-app.firebaseapp.com',
    storageBucket: 'my-stacked-app.appspot.com',
  );
}
